// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahhqtrmybwgqanuqhqje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoaHF0cm15YndncWFudXFocWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzAwMzUsImV4cCI6MjA2MTAwNjAzNX0.9iurBqoLGH1ehh1ZRxMVHozd0YoVROhgOqr6gJ7CjDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);